server:
  port: 8001

spring:
  application:
    name: cloud-provider-hytrix-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}