server:
  port: 8001
spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud_db?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.feng.springcloud.entities       #所有Entity别名类所在包

eureka:
  client:
    #将当前服务注册到Eureka服务端中
    register-with-eureka: true
    #客户端单机默认值为true，使用集群时配合Ribbon负载均衡时一定需要配置
    fetch-registry: true
    service-url:
      #设置与Eureka服务端查询与注册服务的地址
      # Eureka单机服务注册地址
      #defaultZone: http://localhost:7001/eureka/
      # Eureka集群版注册地址，指向所有Eureka服务端节点
      defaultZone: http://eureka.server7001.com:7001/eureka/, http://eureka.server7002.com:7002/eureka/
  instance:
    #Eureka注册实例名
    instance-id: payment8001
    #访问路径显示ip
    prefer-ip-address: true
    #客户端向Eureka服务端发送心跳的时间间隔
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端等待客户端发送心跳时间
    lease-expiration-duration-in-seconds: 2
